### ISSUE TITLE
Initial setup instructions don't work

### ISSUE THREAD

**Issue by dracos** [alphagov/e-petitions#481]
The locations table is only populated in a migration, which you don't get if you use `db:structure:load` (which loads in `structure.sql` which says it includes all the migrations, including 20160210195916, but doesn't appear to include the data created in that migration).

If you instead have empty databases and run `db:migrate`, it appears to all run okay.

**Comment by h-lame** [comment]
Hi @dracos, thanks for bringing this to our attention.  We'll update those instructions and maybe tidy up the seeding of locations in that old migration. The best way to get the locations data now is to use [`FetchCountryRegisterJob`](https://github.com/alphagov/e-petitions/blob/master/app/jobs/fetch_country_register_job.rb).  In the terminal:

```
$ bundle exec rails runner "FetchCountryRegisterJob.perform_now"
```

oughta do it.

Cheers,

Murray

**Comment by dracos** [comment]
Thanks, `db:migrate` also worked as mentioned :) Hope your day has been okay!

**Comment by etagwerker** [comment]
I ran into a couple of problems when following the initial instructions: 

# db/structure.sql won't load with Postgres 9.4.22

I get this error: 

```
root@b9eada3b813a:/usr/src/app# psql -q -U postgres -h db -f db/structure.sql epets_test
psql:db/structure.sql:10: ERROR:  unrecognized configuration parameter "idle_in_transaction_session_timeout"
 set_config
------------

(1 row)

psql:db/structure.sql:16: ERROR:  unrecognized configuration parameter "row_security"
```

When I upgrade to Postgres 9.6.14 this error goes away. 

It is a bit confusing because `.travis.yml` specifies Postgres 9.4 over here: https://github.com/alphagov/e-petitions/blob/be57ce8f306757c9eabb111ac414a432990ca8a2/.travis.yml#L14-L16

Would it be possible to add a version number to the README and/or update the version number for Travis CI? 

# bundle install doesn't work with Ruby 2.2.10p489

From the README: 

```
A few things to know:

You will need ruby 2.2.2
You will need PostgreSQL and Memcached
```

But when I try to install with that version, I get an error from bundler:

```
$ bundle --version
Bundler version 1.16.6
$ ruby --version
ruby 2.2.10p489 (2018-03-28 revision 63023) [x86_64-darwin17]
$ bundle install
Warning: the running version of Bundler (1.16.6) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/..........
nokogiri-1.10.3 requires ruby version >= 2.3.0, which is incompatible with the current version, ruby 2.2.10p489
```

=== 

I made sure that I was running the latest version from `master` so this is all happening at https://github.com/alphagov/e-petitions/commit/2fb49e3a3a60713cf3848a49e8e92c10c01dcb26

**Comment by pixeltrix** [comment]
Closing as we've added a docker-compose config and updated the README in #743
