### ISSUE TITLE
signatures_by_country element not updated on this petition - https://petition.parliament.uk/petitions/131215

### ISSUE THREAD

**Issue by xjpeter** [alphagov/e-petitions#483]
In the JSON data feed, the 'signatures_by_country' element is not updated on this petition - https://petition.parliament.uk/petitions/131215

The total of this column does not equal the total number of votes in the e-petition. Not sure if this is issue #437 ( https://github.com/alphagov/e-petitions/issues/437 ) coming back again.

**Comment by h-lame** [comment]
Hi @xjpeter, 

We've temporarily disabled the signatures by country for the UK because of the high load we're experiencing on that petition.  That said, the number was woefully out of date so I've run a one off calculation for that petition to update it and the figures are closer to the truth now.  It'll continue to drift as time goes on, but we hope to re-enable the live count when load dies down.

Cheers,

Murray
