### ISSUE TITLE
Can't install locally with provided instructions

### ISSUE THREAD

**Issue by virgile-dev** [alphagov/e-petitions#550]
Hello, 

I've been trying to install it a few days go but I get stuck at that part : 
`You will need to set up the config/database.yml. Copy what is in config/database.example.yml and add the password you used earlier for the epets postgres user`

I can't find any file named `database.example.yml`in the config file. 

Could you provide any help?
Thanks!

**Comment by embasbm** [comment]
I pulled master branch and there a file named `database.yml` and that's where I added the lines

>   username: epets
>   password: mysecretpassword

anyone else?

**Comment by pixeltrix** [comment]
I'm going to be updating the README tonight with the latest instructions but if you need to override the authentication details then create a .env.local file like this:

```
DATABASE_URL=postgresql://user:pass@localhost
```

Whatever you do don't put the database name in that file since that will take precedence over the database.yml file and running the tests will blow away any data you've put in there.

**Comment by GRA0007** [comment]
It'd be great if the readme was updated so I didn't have to go hunting for this issue.

**Comment by etagwerker** [comment]
I believe the README is now up to date. The only issue I found when running `./bin/setup` is this one: 

```
== Removing old logs and tempfiles ==

== Restarting application server ==
touch: tmp/restart.txt: No such file or directory
```
