### ISSUE TITLE
Dependent on Constituencies

### ISSUE THREAD

**Issue by bearpig** [alphagov/e-petitions#556]
I'm looking at the feasibility of forking this for the States of Jersey Government and have running locally with no issues (to start poking around at how it's doing certain things). 

A few questions around Constituencies though.

- What role does the check for a Constituency actually do? 
- Is it purely for results on the backend (which Constituencies are concerned the most about a petition) or is it tied up with the actual validation of a signature? 
- Is this only performed on the signature of a petition you've created or any time you sign one?

As I can currently sign a petition on parliament.uk without an issue using Jersey as a location and a valid Jersey postcode (assuming it be far too easy to limit location to just Jersey and have it all work...). 

Thanks for any help.

**Comment by pixeltrix** [comment]
Constituencies are a convenient way to break up the data for analysis and obviously the preferred one since it's a website for the UK Parliament - you could just as easily do counties or in the case of Jersey,  parishes. It performs no role in the validation of signatures (nor does the postcode if you check the codebase) and the lookup is performed for all signatures.

If you're limiting it to people on the island and not ex-pats then you could hard-code country to Jersey and replace the API lookup for constituency with a simple select menu and effectively constituency_id becomes parish_id. You'd also want to remove signatures_by_country from the JSON API since they'd be pointless.

Happy to have a call about it if you want to discuss in more detail.

**Comment by bearpig** [comment]
Ah thought that might be the case - had considered just hardcoding the parishes.
Thanks for the offer, will probably take you up on it.

**Comment by pixeltrix** [comment]
Closing since we've since implemented this in the [Jersey fork][1].

[1]: https://github.com/StatesOfJersey/e-petitions
