### ISSUE TITLE
Signatures on petitions have no integrity

### ISSUE THREAD

**Issue by henricook** [alphagov/e-petitions#690]
With the popularity of the recent 'revoke article 50' petition and rumours of signatories from other countries, fake signatories etc. I thought i'd take a look at the service to see how it all ticks.

It's occurred to me that all you need to sign a petition is a valid post code and an email address. Terribly poor integrity, if the purpose of the service was to verify that the petition was signed by a citizen.

Did you ever consider taking a NINO or passport number to prove citizenship? If there's a NINO -> Address database somewhere that would be even more formidable.

As it stands I think the service is easily disrupted, and as a result easily dismissed by the politicians it's meant to influence - was the intentional strategy? I'd love to work to make it better. Even a 'i'm not a robot' button would go someway towards prevent fraudsters abusing the service.

**Comment by pixeltrix** [comment]
@henricook thanks for your interest in how the Petitions service works.

The Petitions service is designed to promote civic engagement in the democratic process and to do that it provides two outcomes for a petition. If a petition gains 10,000 or more signatures then it must get a response from the government and if it then goes on to 100,000 or more signatures the committee can consider it for a debate in Westminster Hall. What it isn't is a method of verifying identity or a digital voting platform so you need to bear that in mind when considering the design of the system - barriers to signing a petition are the opposite of what is desired because we want to promote civic engagement as much as possible.

You actually overstate the requirements - a valid postcode isn't required because there are situations where a person may not have one. For example a homeless person is still entitled to sign a petition as a British citizen but they don't have an address. Also an overseas British citizen is allowed to sign and may not have a UK address. The postcode is purely there for providing features like informing you of your local MP and signature counts by constituency. It's entirely possible to put in SW1 0AA (the Palace of Westminster) as the postcode if you wanted to abuse the system but we have automated tools to invalidate those signatures because they are invariably spotted.

As for NINO/passport number, again not everyone has those but are still entitled to sign petitions - for example children are entitled to sign but typically wouldn't have a NINO until they are around school leaving age and lots of them wouldn't have passports either. Then there's the issue of keeping that information up to date - we don't even validate the postcode against the PAF database because new ones are generated all the time and why should people living in a new home be prevented from signing a petition? So you can see that any NINO/passport database would similarly be subject lagging updates and errors.

Then there's the issue of privacy - if we asked for a NINO/passport number it would put a great number of people off signing thinking that the government was tracking their political opinions.

Finally, there's just the practicality of using NINO/passport numbers (I can't remember mine of the the top of my head and sure many other people can't) - our intention is to provide an easy to use, accessible system that performs well on a variety of platforms but especially mobile. A lot of people sign in response to sharing on social media platforms and having to dig out passports whilst standing on a crowded commuter train is obviously a barrier to that.

Regarding the 'i'm not a robot' check box, please read the [GOV.UK Service Design Manual][1] on why these are not generally good practise.

If you want to work to make it better, please feel free to do so - we have merged contributions from external developers before, in fact the most popular feature (and ultimately cause of our problems this week) is the automatic signature counting with rolling numbers came from one such pull request (#482). However, please bear in mind the above comments when working on features - we would not merge PRs that added things like captchas and I wouldn't want you to waste your time. However tools that help us identify possible fraud and bring it to our attention are always useful.

Thanks again for your interest.

[1]: https://www.gov.uk/service-manual/technology/using-captchas

**Comment by henricook** [comment]
Thanks for a well considered reply @pixeltrix !
