### ISSUE TITLE
Receiving 403 errors on petition websites

### ISSUE THREAD

**Issue by ParallelParliament** [alphagov/e-petitions#802]
Hi,

The Parallel Parliament server (134.209.27.240) is receiving 403 errors on all e-petition pages. This began around 0800Z on the 21st June 2021.

I presume this block is to do with the level of requests that the site makes on the petition pages. Would it be possible to have some guidance as how we can avoid being restricted in the future, or what issue caused the restrictions to initially be applied?

**Comment by pixeltrix** [comment]
The IP address was added to the block list because of an excessive number of 4XX responses which was flooding our CloudWatch alarms - I'll unblock you for now but please if you get a 410 response from a petition that has been removed due to the request of the creator can you please not make any further requests for that petition, thanks.

**Comment by pixeltrix** [comment]
Okay, that block has been removed - I did try to find out where the requests were coming from so I could let you know but there's no reverse DNS for the ip address and accessing the ip address in a browser returns a 502 error.

**Comment by ParallelParliament** [comment]
Thanks for getting back so quickly and with all the information.

Do you mind providing a petition id/url of a withdrawn petition? I can check the software is handling these cases correctly before reactivating the system.

**Comment by pixeltrix** [comment]
One such petition is https://petition.parliament.uk/petitions/577827

**Comment by ParallelParliament** [comment]
Perfect. Thanks again for being so helpful.
